link = "https://iced-latte.uk/"
first_name = "Test"
last_name = "Testtest"
email = "ilsinyakovmo4@gmail.com"
password = "80000005a"
new_first_name = "Ilyanewnew"
new_last_name = "Sinyakov"
new_email = "new@gmail.com"
